config/routes.rb
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011    Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2012    Daniel Munn <dan.munn@munnster.co.uk>
# Copyright (C) 2011-14 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

RedmineApp::Application.routes.draw do

  #
  # dmsf controller
  #   /projects/<project>/dmsf
  #   [As this controller also processes 'folders' it maybe better to branch into a folder route rather than leaving it as is]
  ##
  post '/projects/:id/dmsf/create', :controller => 'dmsf', :action => 'create'
  get '/projects/:id/dmsf/notify/activate', :controller => 'dmsf', :action => 'notify_activate', :as => 'notify_activate_dmsf'
  get '/projects/:id/dmsf/notify/deactivate', :controller => 'dmsf', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf'
  get '/projects/:id/dmsf/delete', :controller => 'dmsf', :action => 'delete', :as => 'delete_dmsf'
  post '/projects/:id/dmsf/save', :controller => 'dmsf', :action => 'save'
  post '/projects/:id/dmsf/save/root', :controller => 'dmsf', :action => 'save_root'
  post '/projects/:id/dmsf/entries', :controller => 'dmsf', :action => 'entries_operation'
  post '/projects/:id/dmsf/tag_changed', :controller => 'dmsf', :action => 'tag_changed', :as => 'tag_changed'
  post '/projects/:id/dmsf/entries/delete', :controller => 'dmsf', :action => 'delete_entries', :as => 'delete_entries'
  post '/projects/:id/dmsf/entries/email', :controller => 'dmsf', :action => 'entries_email'
  get '/projects/:id/dmsf/entries/download_email_entries', :controller => 'dmsf', :action => 'download_email_entries', :as => 'download_email_entries'
  get '/projects/:id/dmsf/lock', :controller => 'dmsf', :action => 'lock', :as => 'lock_dmsf'
  get '/projects/:id/dmsf/unlock', :controller => 'dmsf', :action => 'unlock', :as => 'unlock_dmsf'
  get '/projects/:id/dmsf/', :controller => 'dmsf', :action => 'show', :as => 'dmsf_folder'
  get '/projects/:id/dmsf/new', :controller => 'dmsf', :action => 'new', :as => 'new_dmsf'
  get '/projects/:id/dmsf/edit', :controller=> 'dmsf', :action => 'edit', :as => 'edit_dmsf'
  get '/projects/:id/dmsf/edit/root', :controller=> 'dmsf', :action => 'edit_root', :as => 'edit_root_dmsf'
  get '/projects/:id/dmsf/trash', :controller => 'dmsf', :action => 'trash', :as => 'trash_dmsf'
  get '/projects/:id/dmsf/restore', :controller => 'dmsf', :action => 'restore', :as => 'restore_dmsf'

  #
  # dmsf_state controller
  #   /projects/<project>/dmsf/state
  ##
  post '/projects/:id/dmsf/state', :controller => 'dmsf_state', :action => 'user_pref_save'

  #
  #  dmsf_upload controller
  #   /projects/<project>/dmsf/upload - dmsf_upload controller
  ##

  post '/projects/:id/dmsf/upload/files', :controller => 'dmsf_upload', :action => 'upload_files'
  post '/projects/:id/dmsf/upload/file', :controller => 'dmsf_upload', :action => 'upload_file'
  post '/projects/:id/dmsf/upload', :controller => 'dmsf_upload', :action => 'upload'
  post '/projects/:id/dmsf/upload/commit', :controller => 'dmsf_upload', :action => 'commit_files'
  post '/projects/:id/dmsf/commit', :controller => 'dmsf_upload', :action => 'commit'
  
  #
  # dmsf_files controller
  #   /dmsf/files/<file id>
  ##
  get '/dmsf/files/:id/notify/activate', :controller => 'dmsf_files', :action => 'notify_activate', :as => 'notify_activate_dmsf_files'
  get '/dmsf/files/:id/notify/deactivate', :controller => 'dmsf_files', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf_files'
  get '/dmsf/files/:id/lock', :controller => 'dmsf_files', :action => 'lock', :as => 'lock_dmsf_files'
  get '/dmsf/files/:id/unlock', :controller => 'dmsf_files', :action => 'unlock', :as => 'unlock_dmsf_files'
  post '/dmsf/files/:id/delete', :controller => 'dmsf_files', :action => 'delete', :as => 'delete_dmsf_files'
  post '/dmsf/files/:id/revision/create', :controller => 'dmsf_files', :action => 'create_revision'
  get '/dmsf/files/:id/revision/delete', :controller => 'dmsf_files', :action => 'delete_revision', :as => 'delete_revision'
  get '/dmsf/files/:id/download', :controller => 'dmsf_files', :action => 'show', :download => '' # Otherwise will not route nil download param
  get '/dmsf/files/:id/download/:download', :controller => 'dmsf_files', :action => 'show', :as => 'download_revision'
  get '/dmsf/files/:id/view', :controller => 'dmsf_files', :action => 'view'
  get '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'show', :as => 'dmsf_file'  
  delete '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'delete'
  get '/dmsf/files/:id/restore', :controller => 'dmsf_files', :action => 'restore', :as => 'restore_dmsf_file'

  #
  # url controller
  #   /dmsf/links/<file id>
  ##
  get '/dmsf/links/:id/restore', :controller => 'dmsf_links', :action => 'restore', :as => 'restore_dmsf_link'
  delete '/dmsf/links/:id', :controller => 'dmsf_links', :action => 'delete'

  # Just to keep backward compatibility with old external direct links
  get '/dmsf_files/:id', :controller => 'dmsf_files', :action => 'show'
  get '/dmsf_files/:id/download', :controller => 'dmsf_files', :action => 'show', :download => ''

  #
  # files_copy controller
  #   /dmsf/files/<file id>/copy
  ##
  post '/dmsf/files/:id/copy/create', :controller => 'dmsf_files_copy', :action => 'create'
  post '/dmsf/files/:id/copy/move', :controller => 'dmsf_files_copy', :action => 'move'
  get '/dmsf/files/:id/copy', :controller => 'dmsf_files_copy', :action => 'new', :as => 'copy_file'

  #
  # folders_copy controller
  #   /dmsf/folders/<folder id>/copy
  ##
  #verify :method => :post, :only => [:copy_to], :render => { :nothing => true, :status => :method_not_allowed }
  post '/dmsf/folders/:id/copy/to', :controller => 'dmsf_folders_copy', :action => 'copy_to'
  get '/dmsf/folders/:id/copy', :controller => 'dmsf_folders_copy', :action => 'new', :as => 'copy_folder'

  #
  # DAV4Rack implementation of Webdav [note: if changing path you'll need to update lib/redmine_dmsf/webdav/no_parse.rb also]
  #   /dmsf/webdav
  mount DAV4Rack::Handler.new(
    :root_uri_path => "#{Redmine::Utils::relative_url_root}/dmsf/webdav",
    :resource_class => RedmineDmsf::Webdav::ResourceProxy,
    :controller_class => RedmineDmsf::Webdav::Controller
  ), :at => "/dmsf/webdav"
  
  # Approval workflow    
  resources :dmsf_workflows do
    member do
      get 'autocomplete_for_user'
      get 'action'
      get 'assign'
      get 'log'
      post 'new_action'
      get 'start'
      post 'assignment'
      get 'new_step'
    end
  end
    
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'add_step', :id => /\d+/, :via => :post
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'remove_step', :id => /\d+/, :via => :delete
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'reorder_steps', :id => /\d+/, :via => :put    
  
  # Links
  resources :dmsf_links do
    member do
      get 'restore'
    end    
  end  
  
end

app/helpers/dmsf_workflows_helper.rb
# encoding: utf-8
#
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011-15 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module DmsfWorkflowsHelper
  
  def render_principals_for_new_dmsf_workflow_users(workflow, dmsf_workflow_step_assignment_id, dmsf_file_revision_id)
    scope = workflow.delegates(params[:q], dmsf_workflow_step_assignment_id, dmsf_file_revision_id)
    principal_count = scope.count
    principal_pages = Redmine::Pagination::Paginator.new principal_count, 10, params['page']
    principals = scope.offset(principal_pages.offset).limit(principal_pages.per_page).all
    
    if dmsf_workflow_step_assignment_id      
      s = content_tag('div',
        content_tag('div', principals_radio_button_tags('user_ids[]', principals), :id => 'users_for_delegate'),
        :class => 'objects-selection')
    else      
      s = content_tag('div',
        content_tag('div', principals_check_box_tags('user_ids[]', principals), :id => 'users'),
        :class => 'objects-selection')
    end

    links = pagination_links_full(principal_pages, principal_count, :per_page_links => false) {|text, parameters, options|
      link_to text, autocomplete_for_user_dmsf_workflow_path(workflow, parameters.merge(:q => params[:q], :format => 'js')), :remote => true      
    }

    s + content_tag('p', links, :class => 'pagination')
    s.html_safe           
  end
  
  def dmsf_workflow_steps_options_for_select(steps)
    options = Array.new
    options << [l(:dmsf_new_step), 0]
    steps.each do |step|
      options << [step.to_s, step]
    end
    options_for_select(options, 0)
  end   
  
  def dmsf_workflows_for_select(project, dmsf_workflow_id)
    options = Array.new        
    DmsfWorkflow.sorted.where(['project_id = ? OR project_id IS NULL', project.id]).each do |wf|
      if wf.project_id
        options << [wf.name, wf.id]
      else
        options << ["#{wf.name} (global)", wf.id]
      end
    end        
    options_for_select(options, :selected => dmsf_workflow_id)
  end  
  
  def dmsf_all_workflows_for_select(dmsf_workflow_id)
    options = Array.new        
    options << ['', 0]    
    DmsfWorkflow.sorted.all.each do |wf|            
      if wf.project_id
        prj = Project.find_by_id wf.project_id
        if User.current.allowed_to?(:manage_workflows, prj)
          # Local approval workflows
          if prj
            options << ["#{wf.name} (#{prj.name})", wf.id]
          else
            options << [wf.name, wf.id]
          end
        end
      else
        # Global approval workflows
        options << [wf.name, wf.id]
      end      
    end            
    options_for_select(options, :selected => dmsf_workflow_id)
  end  
  
  def principals_radio_button_tags(name, principals)
    s = ''
    principals.each do |principal|
      s << "<label>#{ radio_button_tag name, principal.id * 10, false, :id => nil } #{h principal}</label>\n"
    end
    s.html_safe    
  end
end

app/views/dmsf_workflows/_assign.html.erb
<%# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2013   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.%>

<h3 class="title"><%= l(:field_label_dmsf_workflow) %></h3>
<%= form_tag({:controller => 'dmsf_workflows', :action => 'assignment'},
              :method => :post,
              :id => 'assignment-form') do %>
  <%= hidden_field_tag :dmsf_file_revision_id, params[:dmsf_file_revision_id] %>
  <p>
    <%= label_tag('workflow', "#{l(:link_workflow)}:") %>
    <%= select_tag(
        'dmsf_workflow_id',
        dmsf_workflows_for_select(@project, nil))%>
  </p>
  <% if User.current.allowed_to?(:manage_workflows, @project) %>
    <p>
      <%= link_to l(:label_dmsf_workflow_new), new_dmsf_workflow_path, :class => 'icon icon-add' %>
    </p>
  <% end %>
  <p class="buttons">
    <%= submit_tag l(:button_submit), :name => 'commit', :onclick => 'hideModal(this);' %>
    <%= submit_tag l(:button_cancel), :name => 'commit', :onclick => 'hideModal(this);' %>
  </p>
<% end %>

app/views/dmsf_workflows/_log.html.erb
<%# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011-15   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.%>

<h3 class="title"><%= l(:title_dmsf_workflow_log) %></h3>
<p>
  <% if params[:dmsf_file_revision_id].present? %>
    <% revision = DmsfFileRevision.find_by_id(params[:dmsf_file_revision_id]) %>
      <% if revision %>
        <div class="log_header_box">                    
          <div class="log_header_left">
            <%= label_tag 'workflow_name', "#{l(:link_workflow)} #{l(:field_name).downcase}: " %>
            <% if User.current.allowed_to?(:manage_workflows, @dmsf_workflow.project) %>
              <%= link_to @dmsf_workflow.name, dmsf_workflow_path(@dmsf_workflow) %>
            <% else %>
              <%= @dmsf_workflow.name %>
            <% end %>
          </div>
          <div>
            <%= label_tag 'workflow_status', "#{l(:field_status)}: " %>
            <%= revision.workflow_str false %>                
          </div>            
        </div>        
        <div class="tab-content" id="tab-content-members">                     
          <table class="list">
            <thead><tr>
              <th><%= l(:label_dmsf_workflow_step) %></th>
              <th><%= l(:label_user) %> </th>
              <th><%= l(:label_action) %></th>
              <th><%= l(:link_workflow) %></th>
              <th><%= l(:label_note) %></th>
              <th><%= l(:label_date)%></th>              
            </tr></thead>
            <tbody>
            <tr id="step-0" class="even">
                <td class="step"/>
                <td/>
                <td/>
                <td><%= DmsfWorkflowStepAction.workflow_str(0) %></td>
                <td class="note"></td>
                <td/>
              </tr>
              <tr id="step-1" class="odd">
                <td class="step"></td>
                <td><%= link_to_user User.find_by_id(revision.dmsf_workflow_assigned_by) if revision.dmsf_workflow_assigned_by %></td>
                <td><%= DmsfWorkflowStepAction.action_str(DmsfWorkflowStepAction::ACTION_ASSIGN) %></td>
                <td><%= DmsfWorkflowStepAction.workflow_str(DmsfWorkflowStepAction::ACTION_ASSIGN) %></td>
                <td class="note"></td>
                <td><%= format_time(revision.dmsf_workflow_assigned_at) if revision.dmsf_workflow_assigned_at %></td>
              </tr>  
              <tr id="step-2" class="even">
                <td class="step"></td>
                <td><%= link_to_user User.find_by_id(revision.dmsf_workflow_started_by) if revision.dmsf_workflow_started_by %></td>
                <td><%= DmsfWorkflowStepAction.action_str(DmsfWorkflowStepAction::ACTION_START) %></td>
                <td><%= DmsfWorkflowStepAction.workflow_str(DmsfWorkflowStepAction::ACTION_START) if revision.dmsf_workflow_started_by %></td>
                <td class="note"></td>
                <td><%= format_time(revision.dmsf_workflow_started_at) if revision.dmsf_workflow_started_at %></td>
              </tr>
              <% sql = "SELECT c.action, c.note, c.created_at, c.author_id, a.user_id, s.step FROM dmsf_workflow_step_actions c RIGHT JOIN dmsf_workflow_step_assignments a ON a.id = c.dmsf_workflow_step_assignment_id RIGHT JOIN dmsf_workflow_steps s ON s.id = a.dmsf_workflow_step_id WHERE a.dmsf_file_revision_id = #{revision.id} ORDER BY s.step, c.action DESC, c.created_at" %>
              <% result = DmsfWorkflowStep.connection.exec_query sql %>                                                                                                
              <% result.each_with_index do |row, i| %>
                <tr id="step-<%= i + 3 %> " class="<%= cycle 'odd', 'even' %>">
                  <td class="step"><%= row['step'] %></td>
                  <td><%= link_to_user User.find_by_id(row['author_id'].present? ? row['author_id'] : row['user_id']) %></td>
                  <td><%= DmsfWorkflowStepAction.action_str(row['action']) %></td>
                  <td>                    
                    <% if((row['step'].to_i == @dmsf_workflow.dmsf_workflow_steps.last.step) && (revision.workflow == DmsfWorkflow::STATE_APPROVED) && (row['action'] != DmsfWorkflowStepAction::ACTION_DELEGATE)) %>
                      <%= l(:title_approved) %>
                    <% else %>
                      <%= DmsfWorkflowStepAction.workflow_str(row['action']) %>
                    <% end %>
                  </td>
                  <td class="note"><%= row['note'] %></td>
                  <td><%= format_time(row['created_at']) if row['created_at'].present? %></td>
                </tr>
              <% end %>
            </tbody>
          </table>          
        </div>                               
      <% end %>
  <% end %>
</p>

app/views/dmsf_workflows/_new_step_form.html.erb
<%
# encoding: utf-8
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011-15   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<fieldset class="box">
  <legend><%=l(:label_dmsf_workflow_add_approver)%></legend>
  <p><%= label_tag 'user_search', l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>    
  <%= javascript_tag "observeSearchfield('user_search', 'users', '#{ escape_javascript autocomplete_for_user_dmsf_workflow_path(@dmsf_workflow, :dmsf_workflow_step_assignment_id => nil, :dmsf_file_revision_id => nil, :project_id => @project ? @project.id : nil) }')" %>

  <div id="users">
    <%= render_principals_for_new_dmsf_workflow_users(@dmsf_workflow, nil, nil) %>
  </div>
</fieldset>

<fieldset class="box">
  <legend><%= l(:label_dmsf_workflow_step) %></legend>
  <%= select_tag 'step', dmsf_workflow_steps_options_for_select(@steps),
    :id => 'selected_step', :style => "width:100px" %>              
</fieldset>  

app/views/dmsf_workflows/_new_step_modal.html.erb
<%
# encoding: utf-8
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011-15   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<h3 class="title"><%= l(:dmsf_new_step) %></h3>

<%= form_for(:dmsf_workflow, {:url => edit_dmsf_workflow_path(@dmsf_workflow), :method => :post}) do |f| %>  
  <%= render :partial => 'new_step_form' %>
  <p class="buttons">
    <%= submit_tag l(:dmsf_and), :id => 'add-step-and' %>
    <%= submit_tag l(:dmsf_or), :id => 'add-step-or' %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => 'hideModal(this);', :type => 'button' %>    
  </p>
<% end %>

app/views/dmsf_workflows/_steps.html.erb
<%
# encoding: utf-8
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011-15   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<% if @dmsf_workflow.project %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), settings_project_path(@project, :tab => 'dmsf_workflow') %> &#187; <%=h @dmsf_workflow %></h2>
<% else %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), dmsf_workflows_path %> &#187; <%=h @dmsf_workflow %></h2>
<% end %>

<%= labelled_form_for @dmsf_workflow do |f| %>
  <%= error_messages_for 'workflow' %>
  <div class="box tabular">
    <p><%= f.text_field :name, :value => @dmsf_workflow.name, :required => true %><%= submit_tag l(:button_save) %></p>
  </div>  
<% end %>    

<div class="tab-content" id="tab-content-members">  
  <p>  
    <%= link_to l(:dmsf_new_step), new_step_dmsf_workflow_path(@dmsf_workflow), :remote => true, :class => 'icon icon-add' %>
  </p>  
  <% steps = @dmsf_workflow.dmsf_workflow_steps.collect{|s| s.step}.uniq %>
  <% if steps.any? %>
    <table class="list">
      <thead><tr>
        <th><%= l(:label_dmsf_workflow_step) %></th>
        <th><%= l(:label_dmsf_workflow_approval_plural) %></th>
        <th><%=  l(:button_sort)%></th>    
        <th/>
      </tr></thead>
      <tbody>      
      <% steps.each do |i|%>  
        <tr id="step-<%= i %>" class="<%= cycle 'odd', 'even' %> step">            
          <td class="step"><%= i %></td>
          <td class="approval">                
            <% @dmsf_workflow.dmsf_workflow_steps.collect{|s| (s.step == i) ? s : nil}.compact.each_with_index do |step, j| %>
              <% if j != 0 %>
                <b><%= step.soperator %></b>&nbsp
              <% end %>
              <%= link_to_user step.user %>
            <% end %>
          </td>        
          <td class="reorder">  
            <%= reorder_links('workflow_step', {:action => 'edit', :id => @dmsf_workflow, :step => i}, :put) %>
          </td>
          <td class="buttons">      
            <%= delete_link edit_dmsf_workflow_path(@dmsf_workflow, :step => i) %>
          </td>  
        </tr>
      <% end; reset_cycle %>
      </tbody>
    </table>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</div>

app/views/dmsf_workflows/new.html.erb
<%# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011-14 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.%>

<% project = Project.find_by_id params[:project_id] if params[:project_id] %>
<% if project %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), settings_project_path(project, :tab => 'dmsf_workflow') %> &#187; <%=l(:label_dmsf_workflow_new)%></h2>
<% else %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), dmsf_workflows_path %> &#187; <%=l(:label_dmsf_workflow_new)%></h2>
<% end %>

<%= labelled_form_for @dmsf_workflow do |f| %>
  <%= error_messages_for 'dmsf_workflow' %>
  <div class="box tabular">
    <p>      
      <%= f.text_field :name, :value => @dmsf_workflow.name, :size => 25, :maxlength => 255, :required => true %>
    </p>
    <p>      
      <%= label_tag  :label_copy_workflow_from, l(:label_copy_workflow_from) %>
      <%= select_tag('dmsf_workflow_id', dmsf_all_workflows_for_select(params[:dmsf_workflow_id])) %>
    </p>
    <% if project %>
      <p><%= hidden_field_tag :project_id, project.id %></p>
    <% end %>
  </div>
  <%= submit_tag l(:button_create) %>
<% end %>
  
<script type="text/javascript">    
  $('#dmsf_workflow_id').change(function () {
    $('#content').load("<%= url_for(:action => 'new', :project_id => @project) %>", $('#new_dmsf_workflow').serialize());
  });
</script> 